### ISSUE TITLE
File handling (in unittests?) not working on Windows

### ISSUE THREAD

**Issue by moltob** [aranega/pyecore#4]
I am considering further cleanup suggestions, e.g. marking class methods as such etc. I may also at some point suggest one or another modification to the use of decorators and the meta class.

However, before I start doing any of this I need to have green unit tests. Setting this up showed that the current use of resources and their file paths does not seem to be compatible with Windows (which is my main platform right now).

Therefore I have 26 of the current 175 tests failing, most of them being confused about '\' or Windows drive letters.

As you are probably not working on Windows I can offer to generalize. But please let me know if I'm on the right track and that the core of the issue is not something completely different.

**Comment by aranega** [comment]
Indeed, I'm working on Linux, I will check what could be the issue. I thought I was dealing with basic and builtin methods from Python, perhaps I missed some spots, I'm going to check that and try to setup a windows virtual machine to do some tests.

What do you have in mind regarding the decorators and meta-class?

**Comment by aranega** [comment]
So, I've checked and I think the issues were located in the tests themselves: the links towards each test file was expressed in a unix-like fashion. This were a little bit confusing at first as the image I use for my virtual machine is a W10 which is happy with unix-like pathes. 

Anyway, all the tests runs on this image except the one that tries to fetch an XMI from GenMyModel. It seems that there is some issues with SSL certificates. I can't tell if the issue is only related to my virtual machine or if you also have this issue. If everything runs smoothly on your machine, beside the 'http uri' related test, I will disable it.

**Comment by moltob** [comment]
Tests are passing now on Windows 10. I'll retry on Windows 7 on Monday, as that was the machine failing originally, although I could reproduce the original errors also on my personal W10 machine.

Thanks a lot.

Let me just say that I have no intention or expectation that you or anybody else is responding (and fixing) this fast. I merely opened the ticket to have some way discussing the issue and honestly was offering to fix it myself, in pretty much the way you did. I have no issue with doing this, so please don't feel obliged to do fixes like this within an eyeblink like you did now. I am happy to fix or improve if possible as this obviously gives me a chance to learn how you did things.

But nevertheless: thank you very much!

**Comment by moltob** [comment]
Since you asked: on my current machine, _all_ 175 tests are passing now.

**Comment by aranega** [comment]
I didn't felt obliged at all. It was good for me to put my nose again in those tests to see from where the issue could come from and I must say that I was also curious about seting up a dev. env. in Windows. I have a real tendency to forget about Windows. 

Also, I didn't meant to cut your fun (I'm really sorry if you felt it that way), but as you proposed to clean the main code of PyEcore, I was ashamed to let you with a failing playground. Don't worry, next time I will probably not be so fast.

**Comment by moltob** [comment]
Don't worry, all is well. :-) Thanks a lot!

**Comment by moltob** [comment]
On my W7 machine `test_uri_http` is still failing here:


                except OSError as err: # timeout error
    >               raise URLError(err)
    E               urllib.error.URLError: <urlopen error [Errno 11004] getaddrinfo failed>

But probably since at work I am behind an HTTP proxy... I am not sure this kind of test relying on an internet connection is the best idea. Maybe you really do deactivate it.

**Comment by aranega** [comment]
I was worried that this test could cause issues as the one you have. Moreover, it is not very relevant if you want to develop 'offline', as it requires a connection to work... deactivating is indeed a better thing to do. You can remove it if you want, or I can do it if you are on other stuffs.

**Comment by moltob** [comment]
Please go ahead and remove it directly on the develop branch so we spare ourselves the PR game for this. :-)

**Comment by aranega** [comment]
I'm on it, consider it done.
